-- Update test afrika 12 met volledige itinerary data
UPDATE travel_trips
SET
  metadata = jsonb_build_object(
    'itinerary', jsonb_build_array(
      -- Alle 28 dagen volledige data
      jsonb_build_object('day', 1, 'date', '2026-01-05', 'location', 'Johannesburg', 'hotel', jsonb_build_object('name', 'City Lodge Johannesburg Airport, Barbara Road', 'amenities', '["airport shuttle", "pool", "wifi", "restaurant", "bar"]'::jsonb, 'has_restaurant', true), 'activities', '["Aankomst", "Rust uit na lange vlucht", "Apartheid Museum"]'::jsonb, 'highlights', '["Aankomst in Zuid-Afrika"]'::jsonb),
      jsonb_build_object('day', 2, 'date', '2026-01-06', 'location', 'Welgevonden Game Reserve', 'hotel', jsonb_build_object('name', 'Welgevonden Game Reserve Lodge', 'amenities', '["safari", "game drives", "restaurant", "bar"]'::jsonb, 'has_restaurant', true), 'activities', '["Game drives", "Big Five spotting", "Bushveld safari"]'::jsonb, 'highlights', '["Start van safari avontuur"]'::jsonb),
      jsonb_build_object('day', 3, 'date', '2026-01-07', 'location', 'Welgevonden Game Reserve', 'hotel', jsonb_build_object('name', 'Welgevonden Game Reserve Lodge', 'amenities', '["safari", "game drives", "restaurant", "bar"]'::jsonb, 'has_restaurant', true), 'activities', '["Morning game drive", "Evening game drive"]'::jsonb, 'highlights', '["Cheetah en brown hyena spotten"]'::jsonb),
      jsonb_build_object('day', 4, 'date', '2026-01-08', 'location', 'Tzaneen', 'hotel', jsonb_build_object('name', 'Tamboti Lodge Guest House', 'amenities', '["pool", "wifi", "breakfast included"]'::jsonb, 'has_restaurant', false), 'activities', '["Tzaneen Dam", "Agatha Crocodile Ranch", "Locale markten"]'::jsonb, 'highlights', '["Tropische tuin omgeving"]'::jsonb),
      jsonb_build_object('day', 5, 'date', '2026-01-09', 'location', 'Tzaneen', 'hotel', jsonb_build_object('name', 'Tamboti Lodge Guest House', 'amenities', '["pool", "wifi", "breakfast included"]'::jsonb, 'has_restaurant', false), 'activities', '["Verken Tzaneen Dam", "Zwemmen", "Relaxen"]'::jsonb, 'highlights', '["Dag 2 in Tzaneen"]'::jsonb),
      jsonb_build_object('day', 6, 'date', '2026-01-10', 'location', 'Graskop', 'hotel', jsonb_build_object('name', 'Westlodge At Graskop', 'amenities', '["restaurant", "wifi", "breakfast included"]'::jsonb, 'has_restaurant', true), 'activities', '["Blyde River Canyon", "Gods Window", "Bourkes Luck Potholes"]'::jsonb, 'highlights', '["Spectacular canyon views"]'::jsonb),
      jsonb_build_object('day', 7, 'date', '2026-01-11', 'location', 'Graskop', 'hotel', jsonb_build_object('name', 'Westlodge At Graskop', 'amenities', '["restaurant", "wifi", "breakfast included"]'::jsonb, 'has_restaurant', true), 'activities', '["Panorama Route", "Watervallen", "Hiking"]'::jsonb, 'highlights', '["Dag 2 Blyde River gebied"]'::jsonb),
      jsonb_build_object('day', 8, 'date', '2026-01-12', 'location', 'Piet Retief', 'hotel', jsonb_build_object('name', 'Dusk to Dawn Guesthouse', 'amenities', '["wifi", "breakfast included", "pool", "bbq"]'::jsonb, 'has_restaurant', false), 'activities', '["Tussenstop", "Dutch Reformed Church bezoeken"]'::jsonb, 'highlights', '["Rustdag onderweg"]'::jsonb),
      jsonb_build_object('day', 9, 'date', '2026-01-13', 'location', 'St. Lucia', 'hotel', jsonb_build_object('name', 'Ndiza Lodge & Cabanas', 'amenities', '["restaurant", "bar", "pool", "wifi"]'::jsonb, 'has_restaurant', true), 'activities', '["iSimangaliso Wetland Park", "Boottocht", "Hippos en krokodillen"]'::jsonb, 'highlights', '["Aankomst in wetland paradise"]'::jsonb),
      jsonb_build_object('day', 10, 'date', '2026-01-14', 'location', 'St. Lucia', 'hotel', jsonb_build_object('name', 'Ndiza Lodge & Cabanas', 'amenities', '["restaurant", "bar", "pool", "wifi"]'::jsonb, 'has_restaurant', true), 'activities', '["Strand", "Boat cruise", "Wildlife viewing"]'::jsonb, 'highlights', '["Dag 2 in St. Lucia"]'::jsonb),
      jsonb_build_object('day', 11, 'date', '2026-01-15', 'location', 'St. Lucia', 'hotel', jsonb_build_object('name', 'Ndiza Lodge & Cabanas', 'amenities', '["restaurant", "bar", "pool", "wifi"]'::jsonb, 'has_restaurant', true), 'activities', '["Beach day", "Relaxen", "Optional activities"]'::jsonb, 'highlights', '["Laatste dag in St. Lucia"]'::jsonb),
      jsonb_build_object('day', 12, 'date', '2026-01-16', 'location', 'KwaZulu-Natal', 'hotel', jsonb_build_object('name', 'Rhino Ridge Safari Lodge', 'amenities', '["restaurant", "bar", "spa", "pool", "safari", "full board"]'::jsonb, 'has_restaurant', true), 'activities', '["Hluhluwe-iMfolozi game drives", "Big Five", "Safari"]'::jsonb, 'highlights', '["Luxury safari lodge"]'::jsonb),
      jsonb_build_object('day', 13, 'date', '2026-01-17', 'location', 'KwaZulu-Natal', 'hotel', jsonb_build_object('name', 'Rhino Ridge Safari Lodge', 'amenities', '["restaurant", "bar", "spa", "pool", "safari", "full board"]'::jsonb, 'has_restaurant', true), 'activities', '["Morning game drive", "Spa treatments", "Evening drive"]'::jsonb, 'highlights', '["Dag 2 safari experience"]'::jsonb),
      jsonb_build_object('day', 14, 'date', '2026-01-18', 'location', 'Umhlanga', 'hotel', jsonb_build_object('name', 'Tesorino', 'amenities', '["pool", "wifi", "breakfast included", "bar"]'::jsonb, 'has_restaurant', true), 'activities', '["Beach", "Umhlanga Rocks", "Shopping"]'::jsonb, 'highlights', '["Coastal resort town"]'::jsonb),
      jsonb_build_object('day', 15, 'date', '2026-01-19', 'location', 'Durban', 'hotel', jsonb_build_object('name', 'Durban - vlucht naar Port Elizabeth', 'amenities', '[]'::jsonb, 'has_restaurant', false), 'activities', '["Vlucht Durban → Port Elizabeth"]'::jsonb, 'highlights', '["Travel day"]'::jsonb),
      jsonb_build_object('day', 16, 'date', '2026-01-19', 'location', 'Addo Elephant National Park', 'hotel', jsonb_build_object('name', 'Addo Dung Beetle Guest Farm', 'amenities', '["pool", "wifi", "safari", "hiking"]'::jsonb, 'has_restaurant', false), 'activities', '["Addo Elephant National Park safari", "Elephant spotting"]'::jsonb, 'highlights', '["600+ olifanten!"]'::jsonb),
      jsonb_build_object('day', 17, 'date', '2026-01-20', 'location', 'Addo Elephant National Park', 'hotel', jsonb_build_object('name', 'Addo Dung Beetle Guest Farm', 'amenities', '["pool", "wifi", "safari", "hiking"]'::jsonb, 'has_restaurant', false), 'activities', '["Game drive", "Elephant viewing"]'::jsonb, 'highlights', '["Dag 2 Addo"]'::jsonb),
      jsonb_build_object('day', 18, 'date', '2026-01-21', 'location', 'Knysna', 'hotel', jsonb_build_object('name', 'Knysna Manor House', 'amenities', '["wifi"]'::jsonb, 'has_restaurant', false), 'activities', '["Knysna Heads", "Featherbed Nature Reserve", "Lagoon"]'::jsonb, 'highlights', '["Garden Route beginnen"]'::jsonb),
      jsonb_build_object('day', 19, 'date', '2026-01-22', 'location', 'Knysna', 'hotel', jsonb_build_object('name', 'Knysna Manor House', 'amenities', '["wifi"]'::jsonb, 'has_restaurant', false), 'activities', '["Strand", "Vissen", "Whale watching"]'::jsonb, 'highlights', '["Dag 2 Knysna"]'::jsonb),
      jsonb_build_object('day', 20, 'date', '2026-01-23', 'location', 'Knysna', 'hotel', jsonb_build_object('name', 'Knysna Manor House', 'amenities', '["wifi"]'::jsonb, 'has_restaurant', false), 'activities', '["Mountain biking", "Beaches", "Relaxen"]'::jsonb, 'highlights', '["Dag 3 Knysna"]'::jsonb),
      jsonb_build_object('day', 21, 'date', '2026-01-24', 'location', 'Swellendam', 'hotel', jsonb_build_object('name', 'Aan de Oever Guesthouse', 'amenities', '["wifi", "breakfast"]'::jsonb, 'has_restaurant', false), 'activities', '["Cape Dutch architectuur", "Historic town", "Bontebok National Park", "Drostdy Museum", "Lokale winkeltjes"]'::jsonb, 'highlights', '["3e oudste stad Zuid-Afrika"]'::jsonb),
      jsonb_build_object('day', 22, 'date', '2026-01-25', 'location', 'Hermanus', 'hotel', jsonb_build_object('name', 'Whale Coast Ocean Villa', 'amenities', '["beach", "wifi"]'::jsonb, 'has_restaurant', false), 'activities', '["Whale watching", "Cliff Path", "Wine tasting"]'::jsonb, 'highlights', '["Beste whale watching ter wereld"]'::jsonb),
      jsonb_build_object('day', 23, 'date', '2026-01-26', 'location', 'Hermanus', 'hotel', jsonb_build_object('name', 'Whale Coast Ocean Villa', 'amenities', '["beach", "wifi"]'::jsonb, 'has_restaurant', false), 'activities', '["Beach", "Walvissen spotten", "Wijnproeverijen"]'::jsonb, 'highlights', '["Dag 2 Hermanus"]'::jsonb),
      jsonb_build_object('day', 24, 'date', '2026-01-27', 'location', 'Cape Town', 'hotel', jsonb_build_object('name', 'Cape Town Hotel', 'amenities', '[]'::jsonb, 'has_restaurant', false), 'activities', '["Table Mountain", "V&A Waterfront", "City tour"]'::jsonb, 'highlights', '["Aankomst Mother City"]'::jsonb),
      jsonb_build_object('day', 25, 'date', '2026-01-28', 'location', 'Cape Town', 'hotel', jsonb_build_object('name', 'Cape Town Hotel', 'amenities', '[]'::jsonb, 'has_restaurant', false), 'activities', '["Cape Point", "Boulders Beach", "Penguins"]'::jsonb, 'highlights', '["Cape Peninsula tour"]'::jsonb),
      jsonb_build_object('day', 26, 'date', '2026-01-29', 'location', 'Cape Town', 'hotel', jsonb_build_object('name', 'Cape Town Hotel', 'amenities', '[]'::jsonb, 'has_restaurant', false), 'activities', '["Winelands", "Stellenbosch", "Franschhoek"]'::jsonb, 'highlights', '["Wine tasting day"]'::jsonb),
      jsonb_build_object('day', 27, 'date', '2026-01-30', 'location', 'Cape Town', 'hotel', jsonb_build_object('name', 'Cape Town Hotel', 'amenities', '[]'::jsonb, 'has_restaurant', false), 'activities', '["Robben Island", "City Bowl", "Shopping"]'::jsonb, 'highlights', '["Dag 4 Cape Town"]'::jsonb),
      jsonb_build_object('day', 28, 'date', '2026-01-31', 'location', 'Cape Town', 'hotel', jsonb_build_object('name', 'Cape Town Hotel', 'amenities', '[]'::jsonb, 'has_restaurant', false), 'activities', '["Laatste dag", "Souvenirs", "Signal Hill sunset"]'::jsonb, 'highlights', '["Afscheid van Zuid-Afrika"]'::jsonb)
    ),
    'total_days', 28,
    'start_date', '2026-01-05',
    'end_date', '2026-02-01',
    'route', '["Johannesburg", "Welgevonden Game Reserve", "Tzaneen", "Graskop", "Piet Retief", "St. Lucia", "KwaZulu-Natal", "Umhlanga", "Durban", "Port Elizabeth", "Addo Elephant National Park", "Knysna", "Swellendam", "Hermanus", "Cape Town"]'::jsonb,
    'parsed_from_pdf', true
  ),
  custom_context = 'Dit is een 28-daagse rondreis door Zuid-Afrika. De reis start op 5 januari 2026 in Johannesburg en eindigt op 1 februari 2026 in Cape Town.

HOOGTEPUNTEN:
- Welgevonden Game Reserve: Safari met Big Five, cheetah en brown hyena
- Blyde River Canyon: Gods Window, Bourkes Luck Potholes, Panorama Route
- St. Lucia: iSimangaliso Wetland Park met hippos en krokodillen
- Hluhluwe-iMfolozi: Rhino Ridge Safari Lodge met luxury safari experience
- Addo Elephant National Park: Meer dan 600 olifanten!
- Garden Route: Knysna Heads, Featherbed Nature Reserve
- Swellendam: 3e oudste stad van Zuid-Afrika met Cape Dutch architectuur, Bontebok National Park en Drostdy Museum
- Hermanus: Beste whale watching ter wereld
- Cape Town: Table Mountain, Cape Point, Penguins, Winelands'
WHERE id = 'd549627a-7162-4c3b-8460-3aa8aba70337';
