/*
  # Add Subdomain Support to Domain System
  
  1. Changes
    - Add `domain_type` column to distinguish between 'subdomain' and 'custom' domains
    - Add `subdomain_prefix` column to store the subdomain prefix (e.g., 'delmonde')
    - Add `auto_generated` column to track if domain was automatically created
    - Update existing domains to be marked as 'custom' type
    - Create function to generate subdomain from brand name
  
  2. Security
    - Maintains existing RLS policies
    - Ensures subdomain uniqueness
*/

-- Add new columns for subdomain support
ALTER TABLE brand_domains 
ADD COLUMN IF NOT EXISTS domain_type text DEFAULT 'custom' CHECK (domain_type IN ('subdomain', 'custom')),
ADD COLUMN IF NOT EXISTS subdomain_prefix text,
ADD COLUMN IF NOT EXISTS auto_generated boolean DEFAULT false;

-- Update existing domains to be 'custom' type
UPDATE brand_domains 
SET domain_type = 'custom', auto_generated = false
WHERE domain_type IS NULL;

-- Create function to generate subdomain from brand name
CREATE OR REPLACE FUNCTION generate_subdomain_prefix(brand_name text)
RETURNS text AS $$
DECLARE
  prefix text;
  counter int := 0;
  test_prefix text;
BEGIN
  -- Convert to lowercase, replace spaces with hyphens, remove special chars
  prefix := lower(regexp_replace(brand_name, '[^a-zA-Z0-9\s-]', '', 'g'));
  prefix := regexp_replace(prefix, '\s+', '-', 'g');
  prefix := regexp_replace(prefix, '-+', '-', 'g');
  prefix := trim(both '-' from prefix);
  
  -- Limit to 30 characters
  prefix := substring(prefix from 1 for 30);
  
  test_prefix := prefix;
  
  -- Check uniqueness and add counter if needed
  WHILE EXISTS (SELECT 1 FROM brand_domains WHERE subdomain_prefix = test_prefix) LOOP
    counter := counter + 1;
    test_prefix := prefix || '-' || counter;
  END LOOP;
  
  RETURN test_prefix;
END;
$$ LANGUAGE plpgsql;

-- Create unique index on subdomain_prefix for subdomains
CREATE UNIQUE INDEX IF NOT EXISTS idx_brand_domains_subdomain_prefix 
ON brand_domains(subdomain_prefix) 
WHERE domain_type = 'subdomain' AND subdomain_prefix IS NOT NULL;

-- Add comment explaining the columns
COMMENT ON COLUMN brand_domains.domain_type IS 'Type of domain: subdomain (auto-generated) or custom (user-provided)';
COMMENT ON COLUMN brand_domains.subdomain_prefix IS 'Subdomain prefix for auto-generated subdomains (e.g., delmonde for delmonde.ai-travelstudio.nl)';
COMMENT ON COLUMN brand_domains.auto_generated IS 'Whether this domain was automatically generated by the system';
